---
- hosts: all
  become: yes
  tasks:
    - name: Enable required cgroup features.
      lineinfile:
        path: /boot/cmdline.txt
        backrefs: True
        regexp: '(^.+rootwait(\s+(?!cgroup_enable=cpuset cgroup_enable=memory)[\w=/\-\.]+)*)\s*$'
        line: '\1 cgroup_enable=cpuset cgroup_enable=memory'
        state: present
      register: cgroup_features

    - name: Reboot immediately if cgroup features changed.
      reboot:
      when: cgroup_features is changed
